"""
Scenario Library – quantified outcomes and Munin projected improvements for known disasters.
Used by: munin scenarios analyze --output scenarios_analysis.md
"""
from __future__ import annotations

from pathlib import Path
from typing import Dict, Any

SCENARIOS: Dict[str, Dict[str, Any]] = {
    "katrina_2005": {
        "disaster": "Hurricane Katrina",
        "year": 2005,
        "coordination_delay": "3-5 days",
        "deaths_attributed": 1300,
        "damage": "$161B",
        "munin_projected_improvement": {
            "authorization_time": "2-6 hours → 20 minutes",
            "lives_saved": "400-600 (30-45% reduction)",
            "damage_prevented": "$20-40B",
            "confidence": "MEDIUM",
        },
        "evidence": "Official reports cite 'time consuming approval signatures', FEMA-state-local coordination failure",
        "applicability_score": 0.95,
    },
    "fukushima_2011": {
        "disaster": "Fukushima Nuclear",
        "year": 2011,
        "coordination_delay": "7+ hours (venting decision)",
        "deaths_attributed": 51,
        "munin_projected_improvement": {
            "authorization_time": "7 hours → 15 minutes",
            "lives_saved": "20-35 (evacuation coordination)",
            "meltdown_prevention": "POSSIBLE (earlier venting)",
            "confidence": "MEDIUM-HIGH",
        },
        "evidence": "TEPCO-government coordination failure documented; 7-hour venting delay despite approval",
        "applicability_score": 0.92,
    },
    "sept11_2001": {
        "disaster": "September 11 (WTC)",
        "year": 2001,
        "coordination_delay": "Hours (FDNY/NYPD incompatible radios; collapse warning not relayed)",
        "deaths_attributed": 343,
        "munin_projected_improvement": {
            "authorization_time": "Multi-agency alignment in minutes",
            "lives_saved": "50-100+ (faster coordinated withdrawal)",
            "confidence": "MEDIUM",
        },
        "evidence": "FDNY/NYPD/Port Authority communication failure; helicopter warning never reached FDNY",
        "applicability_score": 0.88,
    },
    "uk_floods_2015": {
        "disaster": "Storm Desmond (UK Carlisle)",
        "year": 2015,
        "coordination_delay": "2-6 hours (multi-agency authorisation)",
        "damage": "£500M+ (Cumbria)",
        "munin_projected_improvement": {
            "authorization_time": "2-6 hours → <4 minutes (demo)",
            "damage_prevented": "Estimated 15-25% via faster gate coordination",
            "confidence": "HIGH (demo-validated)",
        },
        "evidence": "Lack of cross-government coordination; 2-6 h authorisation cycle documented",
        "applicability_score": 0.95,
    },
    "texas_2021": {
        "disaster": "Texas Winter Storm (grid failure)",
        "year": 2021,
        "coordination_delay": "N/A – equipment/capacity primary",
        "deaths_attributed": 246,
        "munin_applicable": False,
        "reason": "Equipment failure (frozen turbines); no amount of faster authorisation generates power from broken kit",
        "applicability_score": 0.15,
    },
    "dubai_2024": {
        "disaster": "Dubai Floods",
        "year": 2024,
        "coordination_delay": "N/A – capacity primary",
        "munin_applicable": False,
        "reason": "Drainage overwhelmed; coordination worked, physics didn’t",
        "applicability_score": 0.20,
    },
}


def generate_scenarios_report(scenarios: Dict[str, Dict[str, Any]], output_path: Path) -> None:
    """Write scenarios_analysis.md with quantified impacts and applicability."""
    lines = [
        "# Scenario Library – Quantified Outcomes & Munin Applicability",
        "",
        "Generated by `munin scenarios analyze`.",
        "",
        "## When Munin Applies (coordination/authorisation bottleneck)",
        "",
    ]
    for key, s in scenarios.items():
        if s.get("munin_applicable") is False:
            continue
        lines.append(f"### {s.get('disaster', key)} ({s.get('year', '')})")
        lines.append("")
        lines.append(f"- **Coordination delay (actual):** {s.get('coordination_delay', 'N/A')}")
        if s.get("deaths_attributed"):
            lines.append(f"- **Deaths attributed:** {s['deaths_attributed']}")
        if s.get("damage"):
            lines.append(f"- **Damage:** {s['damage']}")
        imp = s.get("munin_projected_improvement", {})
        if imp:
            lines.append("- **Munin projected improvement:**")
            for k, v in imp.items():
                lines.append(f"  - {k}: {v}")
        lines.append(f"- **Evidence:** {s.get('evidence', 'N/A')}")
        lines.append(f"- **Applicability score:** {s.get('applicability_score', 0):.2f}")
        lines.append("")

    lines.append("## When Munin Does Not Apply")
    lines.append("")
    for key, s in scenarios.items():
        if s.get("munin_applicable") is not False:
            continue
        lines.append(f"### {s.get('disaster', key)} ({s.get('year', '')})")
        lines.append("")
        lines.append(f"- **Reason:** {s.get('reason', 'N/A')}")
        lines.append(f"- **Applicability score:** {s.get('applicability_score', 0):.2f}")
        lines.append("")

    lines.append("---")
    lines.append("Confidence levels: HIGH = demo or strong evidence; MEDIUM = counterfactual from reports; LOW = speculative.")
    lines.append("")

    output_path.write_text("\n".join(lines), encoding="utf-8")
